version: "3.7"

services:
  db:
    build:
      context: .
      dockerfile: .dockerfile
    image: postgres
    container_name: basic-crud-with-go-db
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: books
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/basic-crud-with-go
    volumes:
      - basic-crud-with-go:/var/lib/postgresql/data

volumes:
  basic-crud-with-go: